// lib/data.ts
import {
  QrCode,
  Upload,
  ImageIcon,
  FileText,
  FileImage,
  Zap,
  Image as LucideImage,
  Star,
} from "lucide-react"

export const tools = [
  {
    name: "Image Compressor",
    description: "Compress multiple images at once for web optimization",
    icon: LucideImage,
    href: "/dashboard/image-compressor",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    iconColor: "text-pink-600 dark:text-pink-400",
    new: true,
    popular: true,
  },
  {
    name: "Social Media Bio Generator",
    description: "Generate creative and catchy social media bios using AI",
    icon: Zap,
    href: "/dashboard/social-bio-generator",
    color: "from-yellow-500 to-amber-500",
    bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
    iconColor: "text-yellow-600 dark:text-yellow-500",
    new: true,
    popular: true,
  },
  {
    name: "QR Generator",
    description: "Generate QR codes for any content",
    icon: QrCode,
    href: "/dashboard/qr-generator",
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    iconColor: "text-blue-600 dark:text-blue-400",
    popular: true,
  },
  {
    name: "Image Hosting",
    description: "Upload and host images with URLs",
    icon: Upload,
    href: "/dashboard/image-hosting",
    color: "from-green-500 to-emerald-500",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    iconColor: "text-green-600 dark:text-green-400",
    popular: true,
  },
  {
    name: "Text to Image",
    description: "Generate images from text using AI",
    icon: ImageIcon,
    href: "/dashboard/text-to-image",
    color: "from-purple-500 to-violet-500",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    iconColor: "text-purple-600 dark:text-purple-400",
    new: true,
    popular: true,
  },
  {
    name: "PDF to Text",
    description: "Extract text from PDF documents",
    icon: FileText,
    href: "/dashboard/pdf-to-text",
    color: "from-orange-500 to-amber-500",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    iconColor: "text-orange-600 dark:text-orange-400",
  },
  {
    name: "PDF to JPG",
    description: "Convert PDF pages to images",
    icon: FileImage,
    href: "/dashboard/pdf-to-jpg",
    color: "from-yellow-500 to-orange-500",
    bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
    iconColor: "text-yellow-600 dark:text-yellow-500",
  },
]
